# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43edf630e3445d3371ff2f8da3256b9f"
name = "example-customer-account-api-authentication"
# [START step3-app-url]
application_url = "https://<your-tunnel-url>"
# [END step3-app-url]
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

# [START step2-scopes]
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,customer_read_customers"
# [END step2-scopes]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

# [START step3-customer-auth]
[customer_authentication]
redirect_uris = ["https://<your-tunnel-url>/customer-account-api/callback"]
# [END step3-customer-auth]
